version: '3'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  back:
    container_name: back
    build: 
      context: ./back
    restart: always
    env_file:
     - .env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    working_dir: /usr/src/back
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  front:
    container_name: front
    build:
      context: ./front
    restart: always
    env_file:
    - .env
    depends_on:
      - back
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    working_dir: /usr/src/front
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"